import { Router, Request, Response } from 'express';
import { supabase } from '../lib/supabase.js';
import { v4 as uuidv4 } from 'uuid';

const router = Router();

router.post('/', async (req: Request, res: Response) => {
  try {
    const { fraud_type, description, amount, date, suspect_info } = req.body;

    if (!fraud_type || !description) {
      return res.status(400).json({ error: 'fraud_type and description are required' });
    }

    const now = new Date();
    const complaintId = `CMP-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${uuidv4().slice(0, 8).toUpperCase()}`;

    const complaintText = formatComplaint({
      id: complaintId,
      date: now.toLocaleDateString('en-IN'),
      fraud_type,
      description,
      amount: amount || 0,
      date_of_fraud: date || 'Unknown',
      suspect_info: suspect_info || 'Not provided',
    });

    const complaint = {
      id: uuidv4(),
      complaint_id: complaintId,
      user_id: req.body.user_id || 'anonymous',
      fraud_type,
      description,
      amount: amount || 0,
      date_of_fraud: date || null,
      suspect_info: suspect_info || null,
      complaint_text: complaintText,
      status: 'generated' as const,
      created_at: now.toISOString(),
    };

    const { data, error } = await supabase
      .from('complaints')
      .insert(complaint)
      .select()
      .single();

    if (error) {
      console.error('Supabase insert error:', error);
      return res.status(500).json({ error: 'Failed to save complaint' });
    }

    res.status(201).json(data);
  } catch (err) {
    console.error('Complaint error:', err);
    res.status(500).json({ error: 'Internal server error' });
  }
});

function formatComplaint(params: {
  id: string;
  date: string;
  fraud_type: string;
  description: string;
  amount: number;
  date_of_fraud: string;
  suspect_info: string;
}): string {
  return `CYBER CRIME COMPLAINT
========================
Complaint ID: ${params.id}
Date Filed: ${params.date}

FRAUD DETAILS:
Type of Fraud: ${params.fraud_type}
Date of Incident: ${params.date_of_fraud}
Amount Involved: Rs. ${params.amount.toLocaleString('en-IN')}

DESCRIPTION:
${params.description}

SUSPECT INFORMATION:
${params.suspect_info}

--- 
This complaint was generated by CyberSathi AI.
Please file it at cybercrime.gov.in or call 1930 for immediate assistance.`;
}

export default router;
